### ISSUE TITLE
Is 5.15 kernel supported?

### ISSUE THREAD

**Issue by dvrogozh** [intel-gpu/intel-gpu-cse-backports#1]
https://github.com/intel-gpu/intel-gpu-i915-backports/blob/backport/main/README_UBUNTU.md suggests that 5.15 kernel is supported. For Ubuntu 20.04/22.04 it's recommended to use 5.15.0-50-generic kernel.

However, it's unclear which branch/tag should be used for CSE and PMT drivers which have anything but 5.15 - see output below. Can you, please, clarify:
1. What latest branch/tag should be used for 5.15 support? I suspect that 5.17 tag/branch should be used - that's what I was able to successfully use, but I would like confirmation.
2. Please, redo branching/tagging strategy to step out from specific kernel and/or better document what should actually be used?

```
user@MDS-ATSM-001-Do:~/intel-gpu-cse-backports$ git branch -a
* main
  remotes/origin/HEAD -> origin/main
  remotes/origin/main
  remotes/origin/rhel85
  remotes/origin/rhel86
  remotes/origin/sles15sp3
  remotes/origin/sles15sp4
  remotes/origin/ubuntu514
  remotes/origin/ubuntu517
user@MDS-ATSM-001-Do:~/intel-gpu-cse-backports$ git tag
22WW32_392_RHEL85
22WW32_392_SLES15SP3
22WW32_392_UBUNTU514
22WW32_392_UBUNTU517
22WW32_417_RHEL85
22WW32_417_RHEL86
22WW32_417_SLES15SP3
22WW32_417_UBUNTU514
22WW32_417_UBUNTU517
22WW33_419.38_RHEL85
22WW33_419.38_RHEL86
22WW33_419.38_SLES15SP3
22WW33_419.38_UBUNTU514
22WW33_419.38_UBUNTU517
22WW36_449_RHEL85
22WW36_449_RHEL86
22WW36_449_SLES15SP3
22WW36_449_SLES15SP4
22WW36_449_UBUNTU514
22WW36_449_UBUNTU517
22WW40_449.2_RHEL85
22WW40_449.2_RHEL86
22WW40_449.2_SLES15SP3
22WW40_449.2_SLES15SP4
22WW40_449.2_UBUNTU514
22WW40_449.2_UBUNTU517
22WW45.5_476.14_RHEL86
22WW45.5_476.14_SLES15SP3
22WW45.5_476.14_SLES15SP4
22WW45.5_476.14_UBUNTU514
22WW45.5_476.14_UBUNTU517

```

**Comment by ArturKloniecki** [comment]
1. Kernel 5.15 is supported from Ubuntu517 branch/tags, as you've mentioned.
2. I agree, that the naming is a bit wonky at current state of the repository. Soon-ish we'll be able to provide friendlier solution, once release roll-out catches up with improvements done internally, as the mess is already cleaned up there.

**Comment by eero-t** [comment]
> I agree, that the naming is a bit wonky at current state of the repository. Soon-ish we'll be able to provide friendlier solution, once release roll-out catches up with improvements done internally, as the mess is already cleaned up there.

@ArturKloniecki Could you provide update on the status of this?

**Comment by smuqthya** [comment]
This repo is no longer active. please check Readme. Closing this issue. https://github.com/intel-gpu/intel-gpu-cse-backports
